Update documentation script

diff --git a/bin/docs b/bin/docs
--- a/bin/docs
+++ b/bin/docs
@@ -1,3 +1,18 @@
 #!/bin/sh
 
-stack haddock --haddock-arguments="-o ./docs" "$@"
+
+echo "Building docs..."
+HADDOCK_OUTPUT="$(stack haddock --haddock-arguments="-o ./docs" "$@" 2>&1)"
+MISSING_DOCS="$(echo "$HADDOCK_OUTPUT" | grep "^    ")"
+
+echo "Output:"
+echo "$HADDOCK_OUTPUT"
+
+if [ ! -z "$MISSING_DOCS" ]; then
+  echo "\n\n"
+  echo "Missing docs:"
+  echo "$MISSING_DOCS"
+  exit 1
+fi
+
+exit 0
